version: '3.8'

services:
  langflow:
    image: langflowai/langflow:${SOFTWARE_VERSION_TAG}
    container_name: ${LANGFLOW_CONTAINER_NAME}
    restart: always
    ports:
      - "${LANGFLOW_PORT}:7860"
    depends_on:
      - postgres
    environment:
      LANGFLOW_DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      LANGFLOW_CONFIG_DIR: /var/lib/langflow
      LANGFLOW_SUPERUSER: ${LANGFLOW_SUPERUSER}
      LANGFLOW_SUPERUSER_PASSWORD: ${LANGFLOW_SUPERUSER_PASSWORD}
      LANGFLOW_AUTO_LOGIN: ${LANGFLOW_AUTO_LOGIN}
      LANGFLOW_NEW_USER_IS_ACTIVE: ${LANGFLOW_NEW_USER_IS_ACTIVE}
    volumes:
      - langflow_config:/var/lib/langflow

  postgres:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: False
    volumes:
      - pgadmin_config:/pgadmin4/servers.json

volumes:
  langflow_config:
  postgres_data:
  pgadmin_config:
